### ISSUE TITLE
Make it portrait

### ISSUE THREAD

**Issue by dhruvmodhapp** [creativeIKEP/SelfieSegmentationBarracuda#1]
How to set the camera for a portrait? I tried to change in WebcamInput script's value of width to 1080*1920.  But the composite image looks rotated on real android/ios devices. In unity editor, it works well.

- Segmentation texture size returning processed texture 1080*1920 proper resolution. I have debugged all input texture and composition-processed texture. Returning proper resolution. But somehow composition raw image texture looks not proper, camera view looks rotated.
 
 Any solution for this android/ios portrait selfie segmentation? Really helpful if we can do it for portraite screen
![IMG_2663](https://user-images.githubusercontent.com/46337334/127861785-fc9c5e31-ceab-4cc3-80fe-05fb401f68a4.PNG)

**Comment by rpassaretiwebcore** [comment]
have any success on this?

**Comment by creativeIKEP** [comment]
WebCamTexture may provide images with different orientations on mobile devices (this is not a problem specific to SelfieSegmentationBarracuda).
So you have to handle video rotation using something like [WebCamTexture.videoRotationAngle](https://docs.unity3d.com/2021.2/Documentation/ScriptReference/WebCamTexture-videoRotationAngle.html).

**Comment by creativeIKEP** [comment]
I believe this issue is resolved.
I close this issue.
